# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/vayu/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/vayu

PRODUCT_COPY_FILES += \
    vendor/xiaomi/vayu/proprietary/system/lib/libvolumelistener.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvolumelistener.so \
    vendor/xiaomi/vayu/proprietary/system/lib64/libvolumelistener.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libvolumelistener.so
